resources:
  - name: scriptGit
    type: GitRepo
    configuration:
      path: rahulnlb1/oom
      gitProvider: s_gitHub
      branches:
        include: ^{{gitBranch}}$

pipelines:
 - name: oom_pipeline
   steps:
       - name: S_Bash_0577
         type: Powershell
         configuration:
           inputResources:
              - name: scriptGit
         execution:
           onExecute:
             - echo $res_scriptGit_resourcePath
             - Push-Location $res_scriptGit_resourcePath
             - ls -la
             - fsutil file createnew output.dat 1073741824 #1GB
             - node oom.js
             - Pop-Location
