resources:
  - name: scriptGit
    type: GitRepo
    configuration:
      path: rahulnlb1/oom
      gitProvider: s_gitHub
      branches:
        include: ^{{gitBranch}}$

pipelines:
 - name: oom_pipeline
   configuration:
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - latest
   steps:
       - name: S_Bash_0577
         type: Powershell
         configuration:
           inputResources:
              - name: scriptGit
         execution:
           onExecute:
             - echo $res_scriptGit_resourcePath
             - Push-Location $res_scriptGit_resourcePath
             - fsutil file createnew output.dat 1073741824 #1GB
             - Get-ChildItem
             - node oom.js
             - Pop-Location
